"""Added category_type column

Revision ID: 62248cfb5876
Revises: 
Create Date: 2024-12-05 10:06:27.885094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62248cfb5876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop the table
    op.drop_table('song_recommendations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('song_recommendations_ibfk_1', 'song_categories', ['category'], ['category_id'])
        batch_op.create_index('category_id', ['category'], unique=False)
        batch_op.alter_column('category_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
